module.exports = {
  CLIENT_BASE_URL: process.env.CLIENT_BASE_URL,
  ACTIVATION_TOKEN_SECRET: process.env.ACTIVATION_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  MONGODB_URL: process.env.MONGODB_URL,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
};
